schema_version = "1.0.0"

id = "image_editor_3d"
version = "0.9.0"
name = "Image Editor 3D"
tagline = "Editing image in 3D"
maintainer = "Iribo <iribo.contact2@gmail.com>"
type = "add-on"

website = "https://github.com/iribo0425/image_editor_3d"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
    "2025 Iribo",
]

[permissions]
files = "Import/export image from/to disk"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
]
